spring.datasource.url=jdbc:mysql://localhost:3306/prezence
spring.datasource.username=root
spring.datasource.password=root123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

jwt.secret=${JWT_SECRET:}

# =====================================================
# BIOMETRIA
# =====================================================

biometria.service-key=prezence-dev-2026
biometria.python-url=http://localhost:5000
biometria.validar-path=/biometria/validar

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# BIOMETRIA_SERVICE_KEY=lhSgA8hVcdtfxuRq123KvZ4EaZFTVLn0mJUl88xMQ5BIj8Lri39JfobWdVTXYUut; JWT_SECRET=YAntfNBhgHvkkTLEim4MitAxIKrNVConIbGN0A5P7zH4iLzQIaqoRZB6T